### ISSUE TITLE
APK availability outside PlayStore

### ISSUE THREAD

**Issue by IzzySoft** [aburdiss/ScalePractice#20]
Would you consider making the APK available to those not using Google Play (either because their devices do not support it, Play not being available in their country, or they intentinally decided not to use that walled garden for e.g. privacy reasons)? Ideally, you'd attach it to your tagged releases here (which is where those people would first look). Thanks in advance!

**Comment by aburdiss** [comment]
@IzzySoft That's a great idea. I am new to adding releases on Github, but I believe that I have set it up correctly. Can you let me know if you are able to download and use the APK or App Bundle that I have uploaded?

**Comment by IzzySoft** [comment]
Glad you like the idea :heart_eyes: And thanks for making it reality that fast! Yes, everything looks very fine. I didn't give the APK a try, but my main intention was to make the app available to a wider audience, especially those concerned about their privacy (and the last sentence of your app's description shows that's important to you as well :green_heart:) So let me add another layer: With the next sync tomorrow around 7 pm UTC, your app will [become available here](https://apt.izzysoft.de/fdroid/index/apk/com.scalepractice) in my repo, so those users can easily find, install and keep it updated using any [F-Droid Client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) of their choice (my repo is the largest 3rd party F-Droid repo – only the official [F-Droid.org](https://f-droid.org/) repo is larger (by a factor of 4)).

If you then like what you see, I can send you the metadata I've set up here as PR in [Fastlane format](https://gitlab.com/-/snippets/1895688), so you are in control of how your app is presented. You could even use that for deployment to Play Store if you add the Fastlane binaries – only if you want of course. My updater runs once a day watching out for updates – so all you'd need to do is add a new tag and attach the APK there, as you did now; within 24h that should be available in my repo.

One note: My scanner found your app includes GMS libraries. Those are not libre (they come as proprietary closed-source). If that wasn't there, your app should be eligible for F-Droid.org itself. The `NonFreeDep` label you will see with the listing is to point that out – to those who want only "pure F/LOSS". And to be clear: this is not an accusation, but just a hint :wink:

Thanks a lot again, and I hope you like this outcome as well :smiley:

PS: In case you wonder, I only pulled the "phone screenshots" from Play, skipping the tablet ones for now.

**Comment by aburdiss** [comment]
Thanks for the heads up, I'm always happy to help get my app out to a wider audience, and I am a big fan of increased digital privacy, and those that support or make that easier for others.

I have been investigating fastlane as well, and would appreciate a PR if you have already the information set up, since that looks like it will make deploying to your repository more consistent with the other listings I have.

Thanks for the tip as well, I will take a look into this, although I am pretty sure some of the non free code may be coming from React-Native, what this app is build upon, but there may be a way to strip that out. I've noted that, and will be looking into that in the future.

Thank you for your help on this as well, and for helping free and open source software!

**Comment by IzzySoft** [comment]
> I'm always happy to help get my app out to a wider audience, and I am a big fan of increased digital privacy, and those that support or make that easier for others.

:heart_eyes:

> would appreciate a PR

There you go! Hints inside.

> I am pretty sure some of the non free code may be coming from React-Native

That might well be. Let me check my notes… Maybe some of these can help pinning the culprit:

* `gradle :app:dependencies`  (show gradle dependency tree, see https://stackoverflow.com/a/39020703/3969362)
* `flutter pub deps`          (show Flutter dependency tree)
* `npm list`                  (show NodeJS dependency tree, see https://stackoverflow.com/a/47040266)
* `yarn why mime-db`          (NPM: find out what dragged in a given module, see https://stackoverflow.com/a/54599863)

Nothing specific to RN – if you know the corresponding command, I gladly add it to my notes.

> Thank you for your help on this as well, and for helping free and open source software!

Gladly! :green_heart:
