### ISSUE TITLE
Keep track of scales practiced

### ISSUE THREAD

**Issue by siwei-li** [aburdiss/ScalePractice#23]
Thank you for your neat work!

I am just having this idea of counting the number of times a scale/arpeggio has been practiced. I don't have much experience in React Native but can certainly take a look when I have more free time :)

**Comment by aburdiss** [comment]
@siwei-li Thanks for the idea! I think that would be a helpful feature, and something I might work on when I have the time in the next couple days. If you were interested, and would rather give it a try, I would be happy to accept a Pull Request!

**Comment by aburdiss** [comment]
This has been included in the latest release (v2.8.0) sent for review to the Google, Amazon, and Apple App Stores today!
